rails_app start improvement
uploadcare/uploadcare-rails-example pull request #16
Opened 2022-09-13 10:47 UTC by T0mbery

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-09-14 09:00 UTC, rsedykh requested changes

2022-09-14 09:00 UTC, rsedykh commented on README.md
> +When Docker Compose is installed, build a Docker image by using the `build` directive:
Not sure that I'm familiar with a lingo, but maybe "command", not "directive"?

```suggestion
When Docker Compose is installed, build a Docker image by using the `build` command:
```

2022-09-16 15:38 UTC, rsedykh approved these changes

2022-09-16 15:40 UTC, dmitry-mukhin approved these changes

2022-09-16 15:40 UTC, merged